### ISSUE TITLE
the app crashes

### ISSUE THREAD

**Issue by Emiliano7369** [vashisthg/StartPointSeekBar#10]
App build is ok
Emulator crashes whit this error:

03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: FATAL EXCEPTION: main
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: Process: com.uuaba.uuaba, PID: 2984
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.uuaba.uuaba/com.uuaba.uuaba.User.ProfileActivity_Step3}: android.view.InflateException: Binary XML file line #100: Binary XML file line #100: Error inflating class com.vashisthg.startpointseekbar.StartPointSeekBar
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #100: Binary XML file line #100: Error inflating class com.vashisthg.startpointseekbar.StartPointSeekBar
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #100: Error inflating class com.vashisthg.startpointseekbar.StartPointSeekBar
03-09 15:41:46.138 10085  2984  2984 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vashisthg.startpointseekbar.StartPointSeekBar" on path: DexPathList[[zip

**Comment by Emiliano7369** [comment]
Solved
